apiVersion: v1
kind: Service
metadata:
  name: notification
  namespace: medhead
spec:
  selector:
    app: notification
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      # nodePort: 31500
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification
  namespace: medhead
  labels:
    app: notification
spec:
  replicas: 1
  selector:
    matchLabels:
      app: notification
  template:
    metadata:
      labels:
        app: notification
    spec:
      containers:
        - name: notification
          image: samirguemri/notification-service:latest
          ports:
            - containerPort: 8090