apiVersion: v1
kind: Service
metadata:
  name: notification-service
  namespace: medhead
spec:
  selector:
    app: notification-app
  ports:
    - protocol: TCP
      port: 8090
      targetPort: 8090
      # nodePort: 31500
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: notification-deployment
  namespace: medhead
  labels:
    app: notification-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: notification-app
  template:
    metadata:
      labels:
        app: notification-app
    spec:
      containers:
        - name: notification-app
          image: samirguemri/notification-service:latest
          ports:
            - containerPort: 8090