apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: speciality-application
  namespace: medhead
spec:
  project: default
  source:
    repoURL: "https://github.com/samirguemri/OC__P11_DEVOPS.git"
    path: services/speciality
    targetRevision: HEAD
  destination:
    server: "https://kubernetes.default.svc"
    namespace: medhead
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
