apiVersion: apps/v1
kind: Deployment
metadata:
  name: speciality-deployment
  labels:
    app: speciality-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speciality-service
  template:
    metadata:
      labels:
        app: speciality-service
    spec:
      containers:
        - name: speciality-service
          image: samirguemri/speciality-service:latest
          ports:
            - containerPort: 9443
          env:
            - name: username
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: password
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-url