apiVersion: v1
kind: Service
metadata:
  name: speciality
  namespace: medhead
spec:
  type: NodePort
  selector:
    app: speciality
  ports:
    - protocol: TCP
      port: 9443
      targetPort: 9443
      nodePort: 31800
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: speciality
  namespace: medhead
  labels:
    app: speciality
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speciality
  template:
    metadata:
      labels:
        app: speciality
    spec:
      containers:
        - name: speciality
          image: samirguemri/speciality-service:latest
          # imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 9443
          env:
            - name: username
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: password
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-url
