apiVersion: apps/v1
kind: Deployment
metadata:
  name: speciality-deployment
  labels:
    app: speciality-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: speciality-app
  template:
    metadata:
      labels:
        app: speciality-app
    spec:
      containers:
        - name: speciality-app
          image: samirguemri/speciality-service:latest
          ports:
            - containerPort: 9443
          env:
            - name: username
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: password
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-url

---

apiVersion: v1
kind: Service
metadata:
  name: speciality-service
spec:
  type: NodePort
  selector:
    app: speciality-app
  ports:
    - protocol: TCP
      port: 9443
      targetPort: 9443
      nodePort: 30100