apiVersion: v1
kind: Service
metadata:
  name: hospital
  namespace: medhead
spec:
  selector:
    app: hospital
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      # nodePort: 31600
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital
  namespace: medhead
  labels:
    app: hospital
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hospital
  template:
    metadata:
      labels:
        app: hospital
    spec:
      containers:
        - name: hospital
          image: samirguemri/hospital-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: username
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: password
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-url