apiVersion: v1
kind: Service
metadata:
  name: hospital-service
  namespace: medhead
spec:
  selector:
    app: hospital-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      # nodePort: 31600
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: hospital-deployment
  namespace: medhead
  labels:
    app: hospital-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: hospital-app
  template:
    metadata:
      labels:
        app: hospital-app
    spec:
      containers:
        - name: hospital-app
          image: samirguemri/hospital-service:latest
          ports:
            - containerPort: 8000
          env:
            - name: username
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-user
            - name: password
              valueFrom:
                secretKeyRef:
                  name: mongo-secret
                  key: mongo-password
            - name: DB_URL
              valueFrom:
                configMapKeyRef:
                  name: mongo-config
                  key: mongo-url