apiVersion: v1
kind: Service
metadata:
  name: destination
  namespace: medhead
spec:
  selector:
    app: destination
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
      # nodePort: 31700
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: destination
  namespace: medhead
  labels:
    app: destination
spec:
  replicas: 1
  selector:
    matchLabels:
      app: destination
  template:
    metadata:
      labels:
        app: destination
    spec:
      containers:
        - name: destination
          image: samirguemri/destination-service:latest
          ports:
            - containerPort: 9443