apiVersion: v1
kind: Service
metadata:
  name: destination-service
  namespace: medhead
spec:
  selector:
    app: destination-app
  ports:
    - protocol: TCP
      port: 8443
      targetPort: 8443
      # nodePort: 31700
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: destination-deployment
  namespace: medhead
  labels:
    app: destination-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: destination-app
  template:
    metadata:
      labels:
        app: destination-app
    spec:
      containers:
        - name: destination-app
          image: samirguemri/destination-service:latest
          ports:
            - containerPort: 9443