apiVersion: v1
kind: Service
metadata:
  name: mongodb-express-service
  namespace: medhead
spec:
  type: NodePort
  selector:
    app: mongodb-express-app
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
      nodePort: 30000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-express-deployment
  namespace: medhead
  labels:
    app: mongodb-express-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongodb-express-app
  template:
    metadata:
      labels:
        app: mongodb-express-app
    spec:
      containers:
        - name: mongodb-express-app
          image: mongo-express:latest
          ports:
            - containerPort: 8081
          env:
            - name: ME_CONFIG_MONGODB_ADMINUSERNAME
              value: rootuser
            - name: ME_CONFIG_MONGODB_ADMINPASSWORD
              value: rootpass
            - name: ME_CONFIG_MONGODB_SERVER
              value: mongodb-service
