apiVersion: apps/v1
kind: Deployment
metadata:
  name: medhead-ui-deployment
  namespace: medhead
  labels:
    app: medhead-ui-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: medhead-ui-app
  template:
    metadata:
      labels:
        app: medhead-ui-app
    spec:
      containers:
        - name: medhead-ui-app
          image: samirguemri/medhead-ui-app:latest
          ports:
            - containerPort: 3443
---
apiVersion: v1
kind: Service
metadata:
  name: medhead-ui-service
  namespace: medhead
spec:
  type: NodePort
  selector:
    app: medhead-ui-app
  ports:
    - protocol: TCP
      port: 3443
      targetPort: 3443
      nodePort: 31900
