apiVersion: v1
kind: Service
metadata:
  name: mongodb-service
  namespace: medhead
spec:
  selector:
    app: mongodb-app
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodb-statefulset
spec:
  selector:
    matchLabels:
      app: mongodb-app
  serviceName: "mongodb-app"
  replicas: 1
  template:
    metadata:
      labels:
        app: mongodb-app
    spec:
      containers:
        - name: mongodb
          image: mongo:latest
          ports:
            - containerPort: 27017
          env:
            - name: MONGO_INITDB_ROOT_USERNAME
              value: rootuser
            - name: MONGO_INITDB_ROOT_PASSWORD
              value: rootpass
          volumeMounts:
            - name: data
              mountPath: /data/db
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi
